### PR TITLE
[modifications requises]Cap 271 - link menu to promo

### PR DESCRIPTION
**Pull request by guiachavez**

### CODE REVIEW

**Review by dacosio — CHANGES_REQUESTED** [review]
image
My discount db is empty and this gives me an error.

You have to remove line 96 to 98 in the backend because not having a data in your db shouldn't give you an error 400.

Also, I tried creating a promo before deleting my discount data. It stores the promo in discount but it does not show the menus after saving the coupon.

**Comment by guiachavez** [comment]
updated. I also connect our db to test: i was able to save this data
image
image

**Review by dacosio — CHANGES_REQUESTED** [review]
Created promo does not appear in Promo screen.

**Review by dacosio — CHANGES_REQUESTED** [review]
same error when there are no existing promos. You have to touch the backend as mentioned.

**Pull request merged**
